# Generated by Django 4.1.3 on 2022-12-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('director', models.TextField()),
                ('description', models.TextField()),
                ('poster_url', models.TextField()),
                ('running_time', models.TextField()),
                ('age_rating', models.TextField()),
            ],
            options={
                'db_table': 'movie_movies',
            },
        ),
    ]
