# Generated by Django 4.1.3 on 2022-12-07 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cienmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('seat', models.TextField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cienmas.cinema')),
            ],
            options={
                'db_table': 'movie_theater',
            },
        ),
    ]
