# Generated by Django 4.1.3 on 2022-11-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('detail_address', models.TextField()),
                ('phone', models.TextField()),
                ('shop_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_users.shop_user')),
            ],
            options={
                'db_table': 'shop_deliveries',
            },
        ),
    ]
