# Generated by Django 4.1.3 on 2022-11-30 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('create_at', models.TextField()),
                ('updated_at', models.TextField()),
                ('blog_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_users.blog_users')),
            ],
            options={
                'db_table': 'blog_post',
            },
        ),
    ]
